name: Chrome Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.test }} - ${{ matrix.os }} - Ruby ${{ matrix.ruby }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        test: [chrome, remote_chrome]
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: [ 2.6, 3.0 ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-linux
        if:  matrix.os == 'ubuntu-latest'
      - uses: ./.github/actions/install-chrome
        if:  matrix.os == 'ubuntu-latest'
      - run: |
          echo "COVERAGE=true" >> $GITHUB_ENV
        if: |
          matrix.os == 'ubuntu-latest' ||
          matrix.os == 'macos-latest'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: |
          bundle exec rake spec:${{ matrix.test }}
        env:
          DISPLAY: :99
