name: Edge Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.test }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        test: [edge, remote_edge]
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "COVERAGE=true" >> $GITHUB_ENV
        if: matrix.os == 'macos-latest'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install
      - run: |
          bundle exec rake spec:${{ matrix.test }}
        env:
          DISPLAY: :99
