name: Firefox Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.test }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        test: [firefox, remote_firefox]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-linux
        if:  matrix.os == 'ubuntu-latest'
      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: '93.0'
      - run: |
          echo "COVERAGE=true" >> $GITHUB_ENV
        if: |
          matrix.os == 'ubuntu-latest' ||
          matrix.os == 'macos-latest'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install
      - run: |
          bundle exec rake spec:${{ matrix.test }}
        env:
          DISPLAY: :99
