name: IE Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.test }} Tests
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        test: [ie remote_ie]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install
      - run: |
          bundle exec rake spec:${{ matrix.test }}
        env:
          DISPLAY: :99
