name: Safari Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.test }} Tests
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        test: [safari remote_safari]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/enable-safari
      - run: |
          echo "COVERAGE=true" >> $GITHUB_ENV
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install
      - run: |
          bundle exec rake spec:${{ matrix.test }}
        env:
          DISPLAY: :99
